dist: trusty # Allows old, old Perls
language: perl
perl:
    - "5.8"
    - "5.8.1" # 3-part version to ensure core-only Perl
    - "5.10.1" # 3-part version to ensure core-only Perl
    - "5.34"
    - "blead"

matrix:
    include:
        - perl: "5.34"
          env: COVERAGE=1
    allow_failures:
        - perl: "blead"

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V

install:
    - cpanm -n --skip-satisfied --installdeps .

script:
    - prove -l -s -j$(test-jobs) $(test-files)
